# Generated by Django 5.1.3 on 2024-11-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name1',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
