# Generated by Django 5.1.3 on 2024-11-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_name1_categories_name_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home Appliances', 'Home Appliances')], default='Electronics', max_length=50),
        ),
    ]
