# Generated by Django 5.1.3 on 2024-12-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home Appliances', 'Home Appliances'), ('Groceries', 'Groceries')], default='Electronics', max_length=50),
        ),
    ]
