# Generated by Django 5.1.3 on 2024-12-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Men Clothing', ' Men Clothing'), ('women Clothing', ' Women Clothing'), ('Books', 'Books'), ('Home Appliances', 'Home Appliances'), ('Groceries', 'Groceries')], default='Electronics', max_length=50),
        ),
    ]
